import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import './assets/styles/globals.scss'
import { Inter } from 'next/font/google'
import { persistor, store } from './store/store'
import { PersistGate } from 'redux-persist/integration/react'
import NextAuthProvider from './providers/nextAuthProvider'
import { Session } from 'next-auth'
import { Providers } from './providers/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const queryClient = new QueryClient()

export default async function RootLayout({
  children,
  session
}: {
  children: React.ReactNode,
  session: Session,
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <QueryClientProvider client={queryClient}> */}
          <Providers>
            {/* <PersistGate persistor={persistor}> */}
              {/* <NextAuthProvider session={session}> */}
              {children}
              {/* </NextAuthProvider> */}
            {/* </PersistGate> */}
          </Providers>
        {/* </QueryClientProvider> */}
      </body>
    </html>
  )
}
