"use client";

import type { NextPage } from "next";
import Head from "next/head";
import Heading from "./components/Heading";
import NextAuthProvider from "./providers/nextAuthProvider";
import React from "react";
import { Session } from "next-auth";

interface Props {
  children?: React.ReactNode,
  session: Session | null
}

const Home: NextPage<Props> = ({session}) => {
  console.log('home ses', session);
  
  return (
    <NextAuthProvider session={session}>
      <div>
        <Head>
          <title>Home page</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main>
          <Heading>Home</Heading>
          <h1 className="text-3xl font-bold underline">
            Hello world!
          </h1>
        </main>
      </div>
    </NextAuthProvider>
  );
};

export default Home;