'use client'

import Head from "next/head";
import NextAuthProvider from "./providers/nextAuthProvider";
import React, { useEffect, useState } from "react";
import { PaginationProducts } from "./types";
import productService from "./services/product/product.service";
import CatalogPage from "./components/ui/catalog/CatalogPage";
import { NextPage } from "next";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Session } from "next-auth";
import Layout from "./components/ui/layout/Layout";

interface Props {
  children?: React.ReactNode,
  session: Session
}
const queryClient = new QueryClient()

const Home: NextPage<Props> = ({ session }) => {
  const [data, setData] = useState<PaginationProducts>({ products: [], length: 0 })
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    productService.getAll({ page: 1, perPage: 4 })
      .then((res) => {
        setData(res.data)
        setLoading(false)
      })
  }, [])

  return (
    <div>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <NextAuthProvider session={session}>
          <QueryClientProvider client={queryClient}>
            <Layout>
              <CatalogPage isLoading={loading} products={data.products} length={data.length} />
            </Layout>
          </QueryClientProvider>
        </NextAuthProvider>
      </main>
    </div>
  );
};

export default Home;