'use client'

import Head from "next/head";
import NextAuthProvider from "./providers/nextAuthProvider";
import React, { useEffect, useState } from "react";
import { PaginationProducts } from "./types";
import productService from "./services/product/product.service";
import { NextPage } from "next";
import { Session } from "next-auth";
import Layout from "./components/ui/layout/Layout";
import CatalogWithPagination from "./components/ui/catalog/CatalogWithPagination";
import { prodsPerPage } from "./constants";

interface Props {
  children?: React.ReactNode,
  session: Session
}

const Home: NextPage<Props> = ({ session }) => {
  const [data, setData] = useState<PaginationProducts>({ products: [], length: 0 })
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    productService.getAll({ page: 1, perPage: prodsPerPage })
      .then((resData) => {
        setData(resData)
      }).then(() => setLoading(false))
  }, [])

  return (
    <div>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <NextAuthProvider session={session}>
          <Layout>
            <CatalogWithPagination loading={loading} data={data} length={data.length} />
          </Layout>
        </NextAuthProvider>
      </main>
    </div>
  );
};

export default Home;